### ISSUE TITLE
Error With FaceAligner

### ISSUE THREAD

**Issue by Enthusiast-block** [1297rohit/FaceReco#1]
Hi @1297rohit, @kanchanSharma17 
I was going through your article for face recognition in towardsdatascience.

I got the following error 

line :- 
faceAligned =fa.align(img, gray, dlib.rectangle(x1,y1,x2,y2))

Error :- 
Traceback (most recent call last):
  File "face-recognition.py", line 55, in <module>
    faceAligned =fa.align(img, gray, dlib.rectangle(x1,y1,x2,y2))
  File "/home/user/.local/lib/python3.6/site-packages/imutils/face_utils/facealigner.py", line 68, in align
    M = cv2.getRotationMatrix2D(eyesCenter, angle, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

Can you tell me, how I can resolve this?
Thanks

**Comment by 1297rohit** [comment]
This is a syntax error.
